import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAllTables1764065698629 implements MigrationInterface {
  name = 'CreateAllTables1764065698629';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Tạo bảng CATEGORIES
    await queryRunner.query(
      `CREATE TABLE CATEGORIES (
        CATEGORY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
        CATEGORY_NAME VARCHAR2(100) NOT NULL,
        DESCRIPTION VARCHAR2(200),
        CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_ID)
      )`,
    );

    // Tạo bảng CUSTOMERS
    await queryRunner.query(
      `CREATE TABLE CUSTOMERS (
        CUSTOMER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
        FULL_NAME VARCHAR2(100) NOT NULL,
        PHONE VARCHAR2(15),
        EMAIL VARCHAR2(100),
        ADDRESS VARCHAR2(200),
        CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
      )`,
    );

    // Tạo bảng EMPLOYEES
    await queryRunner.query(
      `CREATE TABLE EMPLOYEES (
        EMPLOYEE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
        FULL_NAME VARCHAR2(100) NOT NULL,
        PHONE VARCHAR2(15),
        POSITION VARCHAR2(50),
        SALARY NUMBER,
        HIRE_DATE DATE,
        CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID)
      )`,
    );

    // Tạo bảng ORDERS
    await queryRunner.query(
      `CREATE TABLE ORDERS (
        ORDER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
        ORDER_DATE DATE NOT NULL,
        CUSTOMER_ID NUMBER NOT NULL,
        EMPLOYEE_ID NUMBER NOT NULL,
        TOTAL_AMOUNT NUMBER NOT NULL,
        CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
      )`,
    );

    // Tạo bảng ORDER_DETAILS
    await queryRunner.query(
      `CREATE TABLE ORDER_DETAILS (
        ORDER_DETAIL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
        ORDER_ID NUMBER NOT NULL,
        PRODUCT_ID NUMBER NOT NULL,
        QUANTITY NUMBER NOT NULL,
        UNIT_PRICE NUMBER NOT NULL,
        CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (ORDER_DETAIL_ID)
      )`,
    );

    // Tạo bảng PRODUCTS (drop nếu tồn tại)
    await queryRunner.query(
      `BEGIN 
         EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS'; 
       EXCEPTION 
         WHEN OTHERS THEN NULL; 
       END;`,
    );
    
    await queryRunner.query(
      `CREATE TABLE PRODUCTS (
        PRODUCT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
        PRODUCT_NAME VARCHAR2(100) NOT NULL,
        PRICE NUMBER NOT NULL,
        QUANTITY NUMBER NOT NULL,
        CATEGORY_ID NUMBER NOT NULL,
        CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
      )`,
    );

    // Thêm Foreign Keys
    await queryRunner.query(
      `ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMERS 
       FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)`,
    );

    await queryRunner.query(
      `ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_EMPLOYEES 
       FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)`,
    );

    await queryRunner.query(
      `ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_ORDERS 
       FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)`,
    );

    await queryRunner.query(
      `ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_PRODUCTS 
       FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)`,
    );

    await queryRunner.query(
      `ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORIES 
       FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop Foreign Keys
    await queryRunner.query(
      `ALTER TABLE PRODUCTS DROP CONSTRAINT FK_PRODUCTS_CATEGORIES`,
    );
    await queryRunner.query(
      `ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_ORDER_DETAILS_PRODUCTS`,
    );
    await queryRunner.query(
      `ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_ORDER_DETAILS_ORDERS`,
    );
    await queryRunner.query(
      `ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_EMPLOYEES`,
    );
    await queryRunner.query(
      `ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_CUSTOMERS`,
    );

    // Revert PRODUCTS table
    await queryRunner.query(`DROP TABLE PRODUCTS`);

    // Drop tables
    await queryRunner.query(`DROP TABLE ORDER_DETAILS`);
    await queryRunner.query(`DROP TABLE ORDERS`);
    await queryRunner.query(`DROP TABLE EMPLOYEES`);
    await queryRunner.query(`DROP TABLE CUSTOMERS`);
    await queryRunner.query(`DROP TABLE CATEGORIES`);
  }
}
